# Generated by Django 3.2.2 on 2021-05-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('reg', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('blood', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'Recruitment',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=500)),
                ('why', models.CharField(max_length=500)),
                ('reg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.recruitment')),
            ],
            options={
                'db_table': 'Apply',
            },
        ),
    ]
