# Generated by Django 3.2.2 on 2021-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='reg',
            field=models.CharField(max_length=15),
        ),
    ]
